// 更新ログデータ
// E-E-A-T (Trust) 向上のため、変更履歴を記録

export interface ChangeLogEntry {
  date: string; // YYYY-MM-DD
  prefectureCode?: string; // 特定の都道府県に関する変更の場合
  type: 'add' | 'update' | 'fix' | 'remove';
  category: 'calculation' | 'data' | 'feature' | 'ui' | 'content' | 'seo';
  title: string;
  description: string;
  sourceUrl?: string;
  sourceName?: string;
}

export const CHANGELOG: ChangeLogEntry[] = [
  {
    date: '2026-07-17',
    type: 'fix',
    category: 'calculation',
    title: '神奈川・大阪・愛知・千葉・埼玉・福岡・北海道の総合得点ツールでも同種の表示崩れを予防修正',
    description:
      '東京都の総合得点ツールで見つかった、極端な数値を入力した際に得点表示が崩れる不具合と同じ仕組みの問題が他7都道府県のツールにも起こり得る状態だったため、あわせて修正しました。各項目は満点の範囲に自動で収まります。',
  },
  {
    date: '2026-07-17',
    prefectureCode: 'tokyo',
    type: 'fix',
    category: 'calculation',
    title: '東京都総合得点ツールで極端な入力時に得点率表示が崩れる不具合を修正',
    description:
      '学力検査点や換算内申の欄に満点を大幅に超える数値を入力した際、得点率が指数表記の異常な値で表示されることがある不具合を修正しました。入力値は各項目の満点の範囲に自動で収まるようにしています。',
  },
  {
    date: '2026-07-17',
    prefectureCode: 'nara',
    type: 'fix',
    category: 'calculation',
    title: '奈良県の内申点計算を2026年3月の制度改定に対応',
    description:
      '奈良県は2026年3月の入試制度改定により、内申点の対象学年・計算方法が変わりました。従来の「中1除外・135点満点」の表示を、標準パターンで中1・中2を含む144点満点の計算に更新し、学校により異なる4パターンをページ上で選べるようにしました。あわせて宮崎県のページに、学力検査との配点比率が非公表である旨の注記を追加しています。',
  },
  {
    date: '2026-07-16',
    type: 'update',
    category: 'ui',
    title: '匿名統計への協力チェックを見やすくリニューアル',
    description:
      '計算結果の下にある「匿名で全国統計に協力する」のチェック欄を、目に留まりやすいカードデザインに刷新しました。収集するのは計算結果の数値のみで、個人を特定できる情報は含まれない点は従来どおりです。',
  },
  {
    date: '2026-07-16',
    type: 'update',
    category: 'data',
    title: '全47都道府県の出典を教育委員会・県公式の一次資料に統一',
    description:
      'これまで一部の都道府県で教育情報サイトを出典として補完していましたが、残る33県について各教育委員会・県公式サイトの入学者選抜要項ページを1件ずつ確認し、全47都道府県の主出典を公式一次資料へ切り替えました。従来の参考ページも第2出典として引き続き確認できます。',
  },
  {
    date: '2026-07-16',
    type: 'update',
    category: 'feature',
    title: '公開API・AI連携(MCP)の利用ルールを整備',
    description:
      '無料利用のレート上限を用途に合わせて見直し、大量の自動アクセスへの制限を強化しました。あわせて、AI連携（MCP）でもAPIキーによる利用計測とレート制限が働くようにしています。サイト内の計算ツールのご利用には影響ありません。最新の上限値は開発者向けページに掲載しています。',
  },
  {
    date: '2026-07-15',
    type: 'update',
    category: 'feature',
    title: 'データ連携・API活用ページを拡充、案内リンクを強化',
    description: '塾・模試運営会社向けのデータ連携ページや、開発者向けAPI活用サンプルを追加しました。あわせて、偏差値診断ページの案内文を検索ニーズに合わせて見直し、合否判定に関する各ツール間の案内リンクを強化しています。',
  },
  {
    date: '2026-07-14',
    type: 'update',
    category: 'ui',
    title: '計算結果画面をリニューアル、一部環境の表示不具合を修正',
    description: '計算結果直後の「保存する」ボタンと、全国の協力者と比較できる「解放コンテンツ」の見た目を刷新しました。また、一部のスマートフォン環境（Android等）で画面下の常設バーが表示されないことがある不具合を修正しています。',
  },
  {
    date: '2026-07-14',
    type: 'update',
    category: 'ui',
    title: 'Cookie確認表示をコンパクト化、公式Xアカウントを開設',
    description: 'サイト訪問時のCookie利用確認を、画面を大きく覆わないシンプルな表示に変更しました（同意の選択肢に変更はありません）。あわせて、開発の裏側や受験データを発信する公式Xアカウントを開設し、フッターからアクセスできるようにしました。',
  },
  {
    date: '2026-07-13',
    type: 'fix',
    category: 'feature',
    title: '不正な自動アクセスへの対策を強化',
    description: '実際の利用者ではない自動アクセスによる無効なクリックを検知・遮断する仕組みを強化し、計測データの正確性を高めました。',
  },
  {
    date: '2026-07-04',
    type: 'update',
    category: 'feature',
    title: '計算結果をLINE・メールで受け取れる「保存」を全ツールに拡大',
    description: '偏差値・内申点・評定平均・総合得点の各ツールで、計算した結果をその場でLINEまたはメールに保存できるようにしました。志望校まで「あと何点」か、最新の合格ボーダー、出願スケジュールを受験本番まで無料でお届けします。スマホでも結果の確認から保存・共有までを一続きで行えるよう、常時表示のかんたん導線も追加しました。',
  },
  {
    date: '2026-07-04',
    type: 'update',
    category: 'ui',
    title: 'ページ表示の高速化と広告まわりの整理',
    description: '全ページで読み込んでいた外部の広告スクリプトを廃止し、ページの表示速度（Core Web Vitals）を改善しました。あわせて、計算ツールのページで内容の薄い広告枠を整理し、読みやすさとツールの使いやすさを優先した構成に見直しています。',
  },
  {
    date: '2026-06-27',
    type: 'update',
    category: 'data',
    title: '内申点の出典を教育委員会など一次情報へ格上げ',
    description: '主要な都道府県について、内申点計算の出典を各都道府県教育委員会・県公式の一次情報へ順次格上げしました。一次照合が完了していない県は「照合中」と正直に明示し、計算根拠の透明性を高めています。品質・出典に関するページの表現も実態に合わせて是正しました。',
    sourceUrl: 'https://www.kyoiku.metro.tokyo.lg.jp/admission/high_school/exam/',
    sourceName: '東京都教育委員会',
  },
  {
    date: '2026-06-26',
    type: 'fix',
    category: 'feature',
    title: '都道府県別ページの表示速度と安定性を改善',
    description: '都道府県別ページの生成方式（事前生成）を見直し、アクセスが集中した際のページ表示エラーを解消しました。あわせて、一部の解説ページが正しく表示されない不具合も修正しています。',
  },
  {
    date: '2026-06-16',
    type: 'add',
    category: 'feature',
    title: '全国47都道府県の「総合得点」計算に対応',
    description: '内申点と当日点（学力検査）を合算した「総合得点」を、全国47都道府県の方式で計算・確認できるツールと解説ページをまとめて新設しました（/total-score）。東京都の1020点満点、神奈川県のS値、大阪府のタイプ別、愛知県の評価方法など、各県の入試制度に沿って算出します。',
  },
  {
    date: '2026-06-15',
    type: 'add',
    category: 'feature',
    title: '教育費シミュレーターと進路・費用ページを拡充',
    description: '高校3年間の費用、公立・私立の実質負担、塾・個別指導の費用、高校〜大学までの進路別教育費、就学支援金などをまとめて確認できるページを拡充しました。文部科学省「子供の学習費調査」などの一次情報に準拠しています。',
    sourceUrl: 'https://www.mext.go.jp/b_menu/toukei/chousa03/gakushuuhi/1268091.htm',
    sourceName: '文部科学省「子供の学習費調査」',
  },
  {
    date: '2026-06-14',
    type: 'add',
    category: 'content',
    title: '三者面談・調査書・推薦入試など目的別ページを多数新設',
    description: '三者面談の準備、調査書（内申書）の仕組み、推薦入試・総合型選抜、実技4教科の対策、内申点の上げ方、不登校からの進路など、受験生・保護者の具体的な悩みに答える専門ページを多数追加しました。関連ツールへの導線も整理しています。',
  },
  {
    date: '2026-06-12',
    type: 'update',
    category: 'feature',
    title: '偏差値ツールの大幅拡張と成績ダッシュボード・学習計画',
    description: '偏差値ページを教科別・志望校別・模試判定・学年別の観点で拡張し、点数⇔偏差値の早見表や上位%の対応表を充実させました。あわせて、中1→中3の内申点・評定平均の推移を記録できる成績ダッシュボードと、目標から逆算する学習計画ジェネレーター（/plan）を新設しています。',
  },
  {
    date: '2026-06-11',
    type: 'add',
    category: 'seo',
    title: 'AI検索向けの最適化・内申点Q&A（/ask）・データ公開',
    description: '主要ページの冒頭に「答え先出し」の要約を設置し、AI検索や強調スニペットで正確に引用されるよう最適化しました。検証済みデータだけで決定論的に回答する内申点クイックアンサー（/ask）を新設。さらに47都道府県の計算方式データをCSVダウンロード・開発者向けAPI（/developers）として公開し、研究・教育目的での引用に対応しました。',
  },
  {
    date: '2026-06-04',
    type: 'fix',
    category: 'seo',
    title: 'タイトルブランド表記の全ページ統一',
    description: '47都道府県・ブログタグ・県トップページで「| My Naishin」ブランドが欠落していた問題を修正。title.templateを廃止し各ページで明示的に管理する方式に統一しました。',
  },
  {
    date: '2026-06-04',
    type: 'fix',
    category: 'feature',
    title: 'Cloudflareビルド環境のメモリ不足を解消',
    description: 'Node.jsヒープ上限を4096MBに引き上げ、型チェックフェーズのOOMクラッシュを修正。2026-06-02以降の全変更が本番に未反映だった問題を解消しました。',
  },
  {
    date: '2026-06-03',
    type: 'fix',
    category: 'seo',
    title: 'タイトル二重ブランド問題を根本修正・CTR改善タイトル刷新',
    description: 'layout.tsxのtitle.templateと各ページの手動ブランドが衝突し「… | My Naishin | My Naishin」と二重化していた問題を解消。47都道府県のタイトルを主要クエリをfront-loadした形式に刷新。定期テスト・内申平均ブログのタイトルをcuriosity-gap型に変更し低CTRを改善。AdSense審査向けauditHideを全ページに拡大。',
  },
  {
    date: '2026-06-03',
    type: 'update',
    category: 'seo',
    title: '偏差値・評定平均ページの大型拡張と大学受験クラスタ対応',
    description: '偏差値ページに点数→偏差値早見表・偏差値→上位%完全対応表・DatasetSchema・模試母集団解説・高校vs大学偏差値を追加。評定平均ページに総合型選抜(+1050%急上昇)・指定校推薦・大学入試向け発展セクションを追設。Google Trends実データに基づいた市場規模最大化戦略の実装。',
  },
  {
    date: '2026-06-02',
    type: 'add',
    category: 'feature',
    title: '高校3年間の費用シミュレーターを追加',
    description: '公立・私立別の入学金・授業料・修学旅行費・制服代など全費用を網羅したシミュレーターを新設（/koukou-hiyou）。文部科学省「子供の学習費調査」一次情報に準拠。フッターの計算ツール欄からもアクセス可能。',
    sourceUrl: 'https://www.mext.go.jp/b_menu/toukei/chousa03/gakushuuhi/1268091.htm',
    sourceName: '文部科学省「子供の学習費調査」',
  },
  {
    date: '2026-06-02',
    type: 'add',
    category: 'seo',
    title: 'AIクローラ方針・llms.txt・Dataset構造化データを実装',
    description: 'AIクローラへの引用許可・学習専用拒否の方針をrobots.txtに明示。llms.txtを新設してAIへのサイト概要を記述。偏差値早見表データにDatasetスキーマを付与し、AI検索エンジンからの引用資産化（GEO対策）を実施。',
  },
  {
    date: '2026-06-02',
    type: 'add',
    category: 'feature',
    title: '保護者リード導線と収益化装置を整備',
    description: 'AdSense審査対応の広告配置最適化・計算結果直後CTA・保護者向けリード送客導線を実装。GSC週次監視スクリプトを追加し、検索順位変動を自動追跡できる運用基盤を整備。',
  },
  {
    date: '2026-05-28',
    type: 'update',
    category: 'seo',
    title: 'GSC実データ駆動の取りこぼし回収バッチ',
    description: '47都道府県ページのタイトル・H1に「2026年度入試対応」を追加、高関連度ブログ15本へ /hensachi 内部リンクを注入、不登校・通信制記事に教育委員会の一次ソースを追補、全ブログヘッダーに「現役中3が運営」E-E-A-Tバッジを設置。',
  },
  {
    date: '2026-05-12',
    type: 'update',
    category: 'ui',
    title: '結果画面をタブ式に刷新・パフォーマンス大幅改善',
    description: '「重要な情報」「詳しく分析」の2タブで情報を整理し、カードが多すぎる問題を解消。レーダーチャートや成績推移グラフなど重いコンポーネントを遅延読み込みに切り替え、初期表示速度を大幅に向上しました。初回訪問時に空の結果画面が表示されるケースも修正しています。',
  },
  {
    date: '2026-05-08',
    type: 'add',
    category: 'content',
    title: '夏休みの戦略記事を追加：復習と予習の黄金比を徹底解説',
    description: '夏休みを制して内申点を爆上げするための「復習＋予習」黄金比を解説した新着記事を公開。時期別の学習スケジュールや、2学期の成績に直結する具体的な取り組みを提案しています。',
  },
  {
    date: '2026-04-29',
    type: 'update',
    category: 'content',
    title: 'ブログさらに＋21記事アップデート！最新の入試トレンドを反映',
    description: '「2026年度最新の内申点トレンド」「逆転合格の戦略」「保護者向けサポートガイド」「新学期チェックリスト」など、受験生と保護者に必要な10本以上の専門コラムを一挙に公開・更新しました。',
  },
  {
    date: '2026-04-29',
    type: 'add',
    category: 'content',
    title: '【東京都】2026年度入試完全ガイド記事の追加',
    description: '分割募集廃止や深沢高校の「10:0」選抜など、2026年度（令和8年度）の最新の都立高校入試制度に対応した詳細解説記事を公開しました。換算内申からESAT-Jまで、網羅的に解説しています。',
    sourceUrl: 'https://www.kyoiku.metro.tokyo.lg.jp/admission/high_school/exam/',
    sourceName: '東京都教育委員会',
  },
  {
    date: '2026-04-29',
    type: 'update',
    category: 'ui',
    title: 'エディトリアル・ブログデザインへの全面刷新',
    description: 'コンテンツの読みやすさと専門性を高めるため、ブログ記事のデザインを雑誌のような「エディトリアル」スタイルに刷新しました。タイポグラフィ、余白、視覚要素を最適化し、長文でも没入して読める環境を整えました。',
  },
  {
    date: '2026-04-22',
    type: 'update',
    category: 'data',
    title: '高校データの大幅改新および上位校情報の公開',
    description: '全国47都道府県の公立高校入試ボーダーラインデータを大幅に更新しました。各都道府県の上位10校を中心に、合格目安となる内申点や当日点の情報を最新の入試結果に基づき収集・公開。志望校選びの精度を向上させました。',
  },
  {
    date: '2026-04-08',
    type: 'update',
    category: 'seo',
    title: '全都道府県別ページの独自コンテンツ化と専門性強化',
    description: '47都道府県それぞれの入試制度に基づいた、より詳細で専門的な解説・FAQ・注意点を大幅拡充. 。各県固有の「内申点の落とし穴」や「2026年度最新傾向」を盛り込み、検索意図への合致度を極限まで高めました。',
  },
  {
    date: '2026-04-08',
    type: 'add',
    category: 'content',
    title: '2026年4月新学期対応コラムの大量追加とサイトマップ同期',
    description: '新学期からの内申点スタートダッシュを決めるための専門コラムを追加。すべての新規コンテンツが検索エンジンに正しくインデックスされるよう、XMLサイトマップおよび内部リンク構造を最適化しました。',
  },
  {
    date: '2026-04-08',
    type: 'update',
    category: 'ui',
    title: '視認性とアクセシビリティの大幅向上',
    description: '長文コンテンツでも読みやすいよう、タイポグラフィの調整、図解要素の追加、スマホでの操作性改善を実施。E-E-A-T向上のため、各記事の執筆根拠となる一次資料へのアクセスを容易にしました。',
  },
  {
    date: '2026-03-20',
    type: 'update',
    category: 'feature',
    title: 'Googlebot巡回最適化と内部リンク強化',
    description: 'トップページに重要ページへの内部リンクを追加し、新着記事セクションを設置。サイトマップとEEAT情報を更新し、検出-未登録ページのインデックス促進を図る。',
  },
  {
    date: '2026-03-20',
    type: 'update',
    category: 'seo',
    title: '構造化データとメタデータの最適化',
    description: 'すべての主要ページにパンくずリスト構造化データを追加。robotsメタタグとcanonical URLを設定し、SEO基盤を強化。',
  },
  {
    date: '2026-03-20',
    type: 'fix',
    category: 'feature',
    title: 'Next.jsビルドエラーを修正',
    description: 'useSearchParams()のSuspense境界の問題を解決し、安定したビルド環境を確保。',
  },
  {
    date: '2026-03-10',
    type: 'update',
    category: 'ui',
    title: 'ブログ全面リニューアル！高品質のデザインに刷新',
    description: '記事ページをプレミアムデザインに全面改修。ヒーローヘッダー・目次・FAQ・CTA・関連記事を追加。ブログ一覧ページもフィーチャード記事＋カテゴリ別表示に刷新。トップページのブログセクションも新記事対応のカード型レイアウトに変更。',
  },
  {
    date: '2026-03-10',
    type: 'update',
    category: 'content',
    title: '都道府県別ガイド記事を大幅加筆',
    description: '「対象学年まとめ」「副教科の倍率まとめ」の2記事を大幅に加筆。学年別対策チェックリスト、倍率シミュレーション表、失敗パターン集、副教科の評定アップのコツなどを追加。FAQスキーマも実装。',
  },
  {
    date: '2026-03-09',
    type: 'add',
    category: 'content',
    title: 'ブログ記事を10本一挙公開！内申点の基礎から受験戦略まで完全網羅',
    description: '「内申点とは？」「内申点の平均」「上げ方7選」「オール3で行ける高校」「内申点が足りない時の戦略」「中1からの対策」「定期テストと内申点」「提出物・授業態度テクニック」「不登校と高校受験」「入試方式別の仕組み」の10記事を追加。検索需要の高いキーワードを網羅し、SEO強化とユーザー価値の向上を実現。',
  },
  {
    date: '2026-03-09',
    type: 'update',
    category: 'feature',
    title: 'SEO最適化・サイト品質の改善',
    description: 'FAQスキーマ構造化データの追加、ブログ記事のメタデータ強化、内部リンク構造の最適化、サイトマップの改善を実施。検索エンジンでの上位表示を目指した包括的な最適化。',
  },
  {
    date: '2026-03-07',
    type: 'fix',
    category: 'content',
    title: 'プライバシーポリシー・お問い合わせページの改善',
    description: 'GA未導入の記述修正、セクション番号重複の修正、AdPlaceholder의テキスト削除、お問い合わせフォームのname属性追加、SNSリンクの修正を実施。',
  },
  {
    date: '2026-02-11',
    type: 'fix',
    category: 'calculation',
    title: 'すべての都道府県を完全網羅！逆算計算ツールが日本全国対応に',
    description: '残りのすべての都道府県（山口県、岡山県、広島県、四国4県、九州・沖縄7県）に逆算計算設定を追加。埼玉県には標準1:1:2モデルの注記も実装。これにより日本全国47都道府県すべてで正確な逆算計算が可能に。',
  },
  {
    date: '2026-02-11',
    type: 'fix',
    category: 'calculation',
    title: '重大な誤り発見！大阪府の内申点計算を完全修正',
    description: '大阪府の内申点計算に重大な誤りを発見し修正。中1・中2は2倍、中3は6倍（正）、タイプⅠ〜Ⅴまで存在（正）、450点満点に対する倍率も修正。すべての都道府県情報を公式情報で再検証済み。',
  },
  {
    date: '2026-02-11',
    type: 'fix',
    category: 'calculation',
    title: '都道府県逆算計算の「残り1割の落とし穴」を完全対策',
    description: '大阪府のタイプ別倍率選択、東京都の実技教科2倍ルールとESAT-J対応、神奈川県の中2・中3内申比率、傾斜配点警告など、Geminiが指摘した隠れたエラー要因すべてに対応しました。',
  },
  {
    date: '2026-02-11',
    type: 'fix',
    category: 'calculation',
    title: 'すべての都道府県逆算計算ロジックを完全修正',
    description: '大阪府（900点満点）、東京都（1020点満点）、神奈川県（S値方式）、千葉県（K値方式）、埼玉県など、各都道府県の正しい入試制度に基づいた逆算計算を実装しました。',
  },
  {
    date: '2026-02-09',
    type: 'fix',
    category: 'content',
    title: 'E-E-A-T信頼性問題を完全修正',
    description: '一次情報リンクの404、不適切表現、断定口調を修正し、広告前提のプライバシーポリシーを強化しました。',
  },
  {
    date: '2026-02-09',
    type: 'add',
    category: 'feature',
    title: 'PWA機能を追加',
    description: 'スマホのホーム画面に追加でき、アプリのように使えるPWA機能を実装しました。',
  },
  {
    date: '2026-02-08',
    type: 'fix',
    category: 'data',
    title: '致命的問題を完全解消',
    description: 'データ整合性・SEO・技術的問題をすべて修正し、100点レベルの品質を達成しました。',
  },
  {
    date: '2026-02-08',
    type: 'fix',
    category: 'data',
    title: 'ブログ記事の県別満点不一致を修正',
    description: '福岡県・埼玉県・北海道の満点表示を正しく修正し、単一データソース化を完了しました。',
  },
  {
    date: '2026-02-08',
    type: 'fix',
    category: 'feature',
    title: 'robots.txtとsitemap.xmlを修正',
    description: 'SEO基盤を修正し、正しいURLと形式で検索エンジンが認識できるようにしました。',
    sourceName: 'robots.txt',
  },
  {
    date: '2026-02-08',
    type: 'add',
    category: 'feature',
    title: '都道府県比較機能を追加',
    description: '最大4県の内申点制度を比較できる機能を追加しました。',
  },
  {
    date: '2026-02-08',
    type: 'add',
    category: 'feature',
    title: 'ツール集ページを追加',
    description: 'すべてのツールをまとめた一覧ページを作成し、ユーザビリティを向上させました。',
  },
  {
    date: '2026-02-08',
    type: 'fix',
    category: 'calculation',
    title: '東京都の計算例矛盾を修正',
    description: '実技倍率を考慮した正確な計算ロジックに修正し、計算例の信頼性を確保しました。',
    prefectureCode: 'tokyo',
  },
  {
    date: '2026-02-08',
    type: 'update',
    category: 'data',
    title: 'データ整合性チェックスクリプトを強化',
    description: 'ブログ記事内の数値整合性チェック機能を追加し、品質保証体制を強化しました。',
  },
  {
    date: '2026-02-08',
    type: 'add',
    category: 'content',
    title: 'TrustInfoコンポーネントを追加',
    description: '信頼性情報（最終確認日・参照資料・更新履歴）を統一表示するコンポーネントを追加しました。',
  },
  {
    date: '2026-02-08',
    type: 'add',
    category: 'content',
    title: 'ToolGuideコンポーネントを追加',
    description: 'ツールの使い方・注意点・よくある間違いを案内するコンポーネントを追加しました。',
  },
  {
    date: '2026-02-08',
    type: 'fix',
    category: 'data',
    title: '愛知県の満点不一致を修正',
    description: 'ブログデータの愛知県満点を45点から90点に修正し、データ整合性を確保しました。',
    prefectureCode: 'aichi',
  },
  {
    date: '2026-02-04',
    type: 'add',
    category: 'feature',
    title: '3導線ナビゲーションを追加',
    description: 'トップページに「計算」「逆算」「制度理解」の3つの目的別導線を追加しました。',
  },
  {
    date: '2026-02-04',
    type: 'add',
    category: 'feature',
    title: '志望校逆算機能を追加',
    description: '目標総合点から必要な当日点を逆算できる機能を追加しました。',
  },
  {
    date: '2026-02-04',
    type: 'update',
    category: 'ui',
    title: '数値入力機能を追加',
    description: 'スライダーに加えて直接数値入力ができるようになりました。',
  },
  {
    date: '2026-02-04',
    type: 'add',
    category: 'feature',
    title: '計算根拠の表示を追加',
    description: '計算結果の下に対象学年・倍率・満点・参照元を常時表示するようになりました。',
  },
  {
    date: '2026-01-30',
    prefectureCode: 'tokyo',
    type: 'update',
    category: 'data',
    title: '東京都の入試情報を更新',
    description: '令和8年度入学者選抜の情報に基づき、ESAT-J加点情報を更新しました。',
    sourceUrl: 'https://www.kyoiku.metro.tokyo.lg.jp/admission/high_school/exam/',
    sourceName: '東京都教育委員会',
  },
  {
    date: '2026-01-30',
    type: 'update',
    category: 'data',
    title: '全47都道府県の計算方式を確認',
    description: '各都道府県教育委員会の公式情報に基づき、計算方式を確認・更新しました。',
  },
  {
    date: '2026-01-28',
    type: 'add',
    category: 'content',
    title: '都道府県別解説ページを追加',
    description: '各都道府県の計算方法・注意点・公式情報リンクをまとめたページを追加しました。',
  },
  {
    date: '2026-01-25',
    type: 'add',
    category: 'feature',
    title: '成績推移グラフを追加',
    description: '過去の計算履歴をグラフで可視化できるようになりました。',
  },
  {
    date: '2026-01-20',
    type: 'add',
    category: 'feature',
    title: '履歴保存機能を追加',
    description: '計算結果を端末に保存し、後から振り返れるようになりました。',
  },
  {
    date: '2026-01-20',
    type: 'add',
    category: 'feature',
    title: '履歴保存機能を追加',
    description: '計算結果を端末に保存し、後から振り返れるようになりました。',
  },
  {
    date: '2026-01-15',
    type: 'add',
    category: 'feature',
    title: 'サービス公開',
    description: 'My Naishin（内申点計算サービス）を公開しました。',
  },
];

export function getRecentChanges(limit: number = 5): ChangeLogEntry[] {
  return CHANGELOG.slice(0, limit);
}

export function getChangesByPrefecture(prefectureCode: string): ChangeLogEntry[] {
  return CHANGELOG.filter((entry) => entry.prefectureCode === prefectureCode);
}

export function getChangesByCategory(category: ChangeLogEntry['category']): ChangeLogEntry[] {
  return CHANGELOG.filter((entry) => entry.category === category);
}
